name: Wechat-Monitor
on:
  schedule:
    # 每30分钟执行一次，可自行改成 */10 十分钟
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Libs
        run: pip install -r requirements.txt
      - name: Run Monitor
        env:
          WX_APPID: ${{ secrets.WX_APPID }}
          WX_APPSECRET: ${{ secrets.WX_APPSECRET }}
          WX_OPENID: ${{ secrets.WX_OPENID }}
          WX_TEMPLATE_ID: ${{ secrets.WX_TEMPLATE_ID }}
        run: python main.py
